/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u          /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u            /*!<@brief Pull Enable: Enables */
#define PORT2_PCR20_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR21_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR22_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT4_PCR3_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT4_PCR6_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT4_PCR7_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT4_6 (number 27), E
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_E_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_E_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_E_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_E_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_E_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_E_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_E_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT4_7 (number 28), RS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_RS_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_RS_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_RS_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_RS_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_RS_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_RS_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_RS_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT2_1 (number 34), D0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_D0_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D0_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_D0_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_D0_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_D0_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D0_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_D0_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT2_20 (number 55), D1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_D1_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_D1_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_D1_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_D1_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D1_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_D1_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT2_21 (number 56), D2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_D2_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_D2_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_D2_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_D2_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D2_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_D2_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_3 (number 24), D3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_D3_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D3_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_D3_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_D3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_D3_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D3_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_D3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_12 (number 92), D4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_D4_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D4_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_D4_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_D4_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_D4_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D4_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_D4_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_13 (number 91), D5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_D5_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D5_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_D5_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_D5_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_D5_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D5_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_D5_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_15 (number 89), D6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_D6_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D6_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_D6_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_D6_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_D6_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D6_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_D6_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_16 (number 88), D7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_D7_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D7_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITDEBUG_UARTPINS_D7_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_D7_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_D7_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_D7_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_D7_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_22 (number 81), KEY1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_KEY1_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_KEY1_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_KEY1_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_KEY1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_KEY1_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_KEY1_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT3_17 (number 87), KEY2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_KEY2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_KEY2_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_KEY2_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_KEY2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_KEY2_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_KEY2_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT3_1 (number 105), KEY3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_KEY3_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_KEY3_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_KEY3_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_KEY3_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_KEY3_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_KEY3_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT2_22 (number 57), KEY4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_KEY4_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_KEY4_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_KEY4_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_KEY4_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_KEY4_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_KEY4_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORT3_18 (number 86), LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_RED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RED_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_19 (number 85), LED_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT3_21 (number 82), LED_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_BLUE_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PORT1_7 (number 144), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW2_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_6 (number 115), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT2_PCR20_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR21_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT4_PCR3_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT4_PCR6_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT4_PCR7_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT4_7 (number 28), RS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_RS_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_RS_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_RS_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_RS_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_RS_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_RS_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_RS_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT4_6 (number 27), E
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_E_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_E_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_E_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_E_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_E_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_E_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_E_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_1 (number 34), D0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_D0_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_D0_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_D0_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_D0_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_D0_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_D0_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_D0_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT2_20 (number 55), D1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_D1_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_D1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_D1_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_D1_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_D1_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_D1_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_D1_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT2_21 (number 56), D2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_D2_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_D2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_D2_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_D2_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_D2_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_D2_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_D2_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT4_3 (number 24), D3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_D3_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_D3_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_D3_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_D3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_D3_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_D3_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_D3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT3_12 (number 92), D4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_D4_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_D4_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_D4_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_D4_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_D4_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_D4_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_D4_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_13 (number 91), D5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_D5_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_D5_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_D5_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_D5_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_D5_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_D5_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_D5_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_15 (number 89), D6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_D6_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_D6_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_D6_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_D6_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_D6_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_D6_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_D6_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_16 (number 88), D7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITI2CPINS_D7_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITI2CPINS_D7_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITI2CPINS_D7_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITI2CPINS_D7_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITI2CPINS_D7_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITI2CPINS_D7_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITI2CPINS_D7_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2CPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI3CPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSPIPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCANPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSLCDPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
